# Generated by Django 4.1.7 on 2023-03-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': '1. Banners'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': '3. Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '2. Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '5. Products'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name_plural': '4. Sizes'},
        ),
    ]
